### PR TITLE
Fix work stealing ACKs and work recovery

### LINKED ISSUE #51: Handle delayed/lost `AckWorkReceived`
### Potential Problem

When sending work to another node, the sending node waits for an acknowledgement of arrival. If that doesn't arrive within 5 seconds it is assumes that the work wasn't received and it is readded to the sender's own queue. 
This leads to this work (and all work generated from these candidates) to be done twice if the work was received, but the acknowledgment message (`AckWorkReceived`) got lost or delayed.  

### Potential Solution
The work sender could resend the work instead of readding it to it's own queue. If the reason no acknowledgement was received was an overload of the system, though, this might worsen the problem. (And the receiving node would have to check received work for duplicates before adding it to its own queue)

### PR DESCRIPTION
**Pull request by SebastianSchmidl**
### Proposed Changes

Implement protocol according to:

1. Watch actor ref of thief in sender
2. Send work over
3. If ACK received de-watch thief
4. If `Terminated` received, recover work to own queue
5. Use `akka.actor.remote.artery.transport = tcp` as transport configuration

see [Meeting notes from 2019-06-25](https://github.com/CodeLionX/dODo/blob/doc/minutes/doc/minutes/2019-06-25_seminar_meeting.md#how-to-ensure-work-stealing-worked)

### Type of Changes

- [ ] Feature
- [x] Bug fix
- [ ] Refactoring

### Related

- fixes #51

### CODE REVIEW

**Comment by SebastianSchmidl** [comment]
Changing the transport to `tcp` makes the cluster components not work correctly anymore. The connection to a left node will be re-established after the left node has come back and the `Terminated()` message will be received thereafter ... strange ...

The TCP system is trying to reconnect with the left node constantly while the other node is down (even after a couple of minutes):
```
[18:31:56.234 WARN ] kka.stream.Log(akka://dodo-system/system/StreamSupervisor-0)| [outbound connection to [akka://dodo-system@127.0.0.1:7878], control stream] Upstream failed, cause: StreamTcpException: Tcp command [Connect(127.0.0.1:7878,None,List(),Some(5000 milliseconds),true)] failed because of java.net.ConnectException: Connection refused
[18:31:56.235 WARN ]                   RestartWithBackoffFlow(akka://dodo-system)| Restarting graph due to failure. stack_trace:  (akka.stream.StreamTcpException: Tcp command [Connect(127.0.0.1:7878,None,List(),Some(5000 milliseconds),true)] failed because of java.net.ConnectException: Connection refused)
```

**Comment by SebastianSchmidl** [comment]
On my laptop it works like a charm. So it must depend on my computer.

File: src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala [hunk 1]
```diff
@@ -411,14 +405,15 @@ class ODMaster(inputFile: Option[File])
...
-    idleWorkers = idleWorkers.filter(worker => {
-      candidateQueue.sendBatchTo(worker, reducedColumns) match {
-        case scala.util.Success(_) =>
-          log.debug("Scheduling task to check OCD to idle worker {}", worker.path.name)
-          false
-        case scala.util.Failure(_) => true
-      }
-    })
-  }
+  def sendWorkToIdleWorkers(): Unit =
```
Comment (julkw) [inline src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala:408]: usually we encase functions with {}, so I'd add them here

**Review by julkw — APPROVED** [review]
